### ISSUE TITLE
Utilizar o Pandas para plotar gráficos

### ISSUE THREAD

**Issue by orlandosaraivajr** [Ataide-Araujo/MeuETL#1]
Conforme conversamos no meet, pode ser interessante utilizar a biblioteca Pandas ( https://pandas.pydata.org/ ) para plotar gráficos

**Comment by Ataide-Araujo** [comment]
Feito parcialmente com pandas (para gerar o df e trabalhar em cima dele), utilizei a matplotlib para criar gráficos em barra.
