### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by pedrohsbarbosa99** [Ataide-Araujo/MeuETL#2]
Sugiro adicionar requirements.txt e passo a passo de como rodar o projeto

**Comment by Ataide-Araujo** [comment]
Feito (acredito que sim ^^)
Adicionei junto um ignore já também.

**Comment by orlandosaraivajr** [comment]
Adicionar requirements.txt auxilia a replicar em qualquer máquina o ambiente em que foi desenvolvido. Ficou muito bacana.
