### ISSUE TITLE
Feedback 23-junho-2022

### ISSUE THREAD

**Issue by orlandosaraivajr** [Ataide-Araujo/MeuETL#3]
O projeto está avançando. Registro algumas sugestões: 

- Ficou bem legal o README.md 
Poderia incluir no markdown como rodar no console. Exemplo:

```console
git clone ...
```

- Como testar o código e/ou as estruturas internas ? Crie testes ;)
- O projeto está em evolução. Foque em ter um mínimo que funcione, com testes, para avançar e refatorar o código.

**Comment by mateusyamaguti** [comment]
O projeto está tomando um corpo bem elegante, a divisão das responsabildiades dentro do projeto também está adequada.
Segue abaixo algumas sugestões:
- Sugiro fazer as instruções semelhantes também para aplicação em ambiente Windows. por exemplo no campo "Ativar o ambiente virtual" -> MeuETL\Scripts\activate.bat
- Além disso, sugiro fazer a criação de testes. Esse tutorial básico pode lhe ajudar no início: https://github.com/luizalabs/tutorial-python-brasil/blob/main/tdd.md
- Como também, você pode usar a lib coverage (https://pypi.org/project/coverage/) para indicar onde falta a realizar teste.

**Comment by Ataide-Araujo** [comment]
Adicionado como clonar o projeto, instalação da biblioteca necessária para a máquina virtual, adicionado alguns testes (foi adicionado tratativas para possíveis erros de retorno das classes a partir...), como rodar os testes, como rodar no windows.
